using Core.Database.Entities;
using Core.Models;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace Core.Database;

public abstract class CoreDbContext<TAuditLogEntity> : DbContext where TAuditLogEntity : CoreAuditLogEntity
{
    public CoreDbContext(DbContextOptions<CoreDbContext<TAuditLogEntity>> options) : base(options)
    {
    }

    public DbSet<TAuditLogEntity> AuditLogs { set; get; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        ConfigureModelCreating(modelBuilder);
    }
    public abstract void ConfigureModelCreating(ModelBuilder modelBuilder);

    public virtual async Task<int> SaveChangesAsync(AuditLogCreateDto auditLogCreateDto = null)
    {
        var auditEntries = new List<AuditEntry<TAuditLogEntity>>();
        if (auditLogCreateDto != null)
            auditEntries = OnBeforeSaveChanges(auditLogCreateDto);
        var result = await base.SaveChangesAsync();
        await OnAfterSaveChanges(auditEntries);
        return result;
    }

    private List<AuditEntry<TAuditLogEntity>> OnBeforeSaveChanges(AuditLogCreateDto auditLogCreateDto)
    {
        ChangeTracker.DetectChanges();
        var auditEntries = new List<AuditEntry<TAuditLogEntity>>();
        foreach (var entry in ChangeTracker.Entries())
        {
            if (entry.Entity is CoreAuditLogEntity || entry.State == EntityState.Detached || entry.State == EntityState.Unchanged)
                continue;
            var auditEntry = new AuditEntry<TAuditLogEntity>(entry)
            {
                Method = auditLogCreateDto.Method,
                TableName = entry.Entity.GetType().Name,
                CreatedBy = auditLogCreateDto.CreatedBy
            };
            auditEntries.Add(auditEntry);
            foreach (var property in entry.Properties)
            {
                if (property.IsTemporary)
                {
                    // value will be generated by the database, get the value after saving
                    auditEntry.TemporaryProperties.Add(property);
                    continue;
                }

                string propertyName = property.Metadata.Name;

                if (property.Metadata.IsPrimaryKey())
                {
                    auditEntry.KeyValues[propertyName] = property.CurrentValue;
                    continue;
                }

                switch (entry.State)
                {
                    case EntityState.Added:
                        auditEntry.Type = AuditLogType.Create;
                        auditEntry.NewValues[propertyName] = property.CurrentValue;
                        break;
                    case EntityState.Deleted:
                        auditEntry.Type = AuditLogType.Delete;
                        auditEntry.OldValues[propertyName] = property.OriginalValue;
                        break;
                    case EntityState.Modified:
                        if (auditEntry.Method == "DELETE")
                        {
                            auditEntry.Type = AuditLogType.Delete;
                            auditEntry.OldValues[propertyName] = property.OriginalValue;
                        }
                        else
                        {
                            if (property.IsModified)
                            {
                                if (JsonConvert.SerializeObject(property.OriginalValue) !=
                                    JsonConvert.SerializeObject(property.CurrentValue))
                                    auditEntry.ChangedColumns.Add(propertyName);
                                auditEntry.Type = AuditLogType.Update;
                                auditEntry.OldValues[propertyName] = property.OriginalValue;
                                auditEntry.NewValues[propertyName] = property.CurrentValue;
                            }
                        }
                        break;
                }
            }
        }
        foreach (var auditEntry in auditEntries.Where(_ => !_.HasTemporaryProperties))
        {
            AuditLogs.Add((TAuditLogEntity)auditEntry.ToAudit());
        }

        return auditEntries.Where(_ => _.HasTemporaryProperties).ToList();
    }

    private Task OnAfterSaveChanges(List<AuditEntry<TAuditLogEntity>> auditEntries)
    {
        if (auditEntries == null || auditEntries.Count == 0)
            return Task.CompletedTask;

        foreach (var auditEntry in auditEntries)
        {
            foreach (var prop in auditEntry.TemporaryProperties)
            {
                if (prop.Metadata.IsPrimaryKey())
                {
                    auditEntry.KeyValues[prop.Metadata.Name] = prop.CurrentValue;
                }
                else
                {
                    auditEntry.NewValues[prop.Metadata.Name] = prop.CurrentValue;
                }
            }

            AuditLogs.Add((TAuditLogEntity)auditEntry.ToAudit());
        }

        return SaveChangesAsync();
    }
}